# Generated by Django 5.1 on 2026-01-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('Method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], max_length=50)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('TransactionRef', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
    ]
