# Generated by Django 5.1 on 2025-12-31 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('Method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], max_length=50)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('TransactionRef', models.CharField(blank=True, max_length=100, null=True)),
                ('RentalID', models.ForeignKey(db_column='RentalID', on_delete=django.db.models.deletion.CASCADE, to='rentals.rental')),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
