# Generated by Django 5.1 on 2025-12-29 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_alter_car_table_alter_carcategory_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlistid', models.AutoField(db_column='WishlistID', primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_column='DateAdded')),
                ('car', models.ForeignKey(db_column='CarID', on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='cars.car')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist',
                'ordering': ['-date_added'],
                'unique_together': {('user', 'car')},
            },
        ),
    ]
