# Generated by Django 5.1 on 2025-12-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rentalid', models.AutoField(db_column='RentalID', primary_key=True, serialize=False)),
                ('startdate', models.DateField(db_column='StartDate')),
                ('enddate', models.DateField(db_column='EndDate')),
                ('duration', models.IntegerField(db_column='Duration')),
                ('totalamount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Rental',
                'managed': False,
            },
        ),
    ]
