# Generated by Django 5.1 on 2026-01-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'managed': False},
        ),
    ]
