# Generated by Django 5.1 on 2026-01-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarReturn',
            fields=[
                ('returnid', models.AutoField(db_column='ReturnID', primary_key=True, serialize=False)),
                ('returndatetime', models.DateTimeField(db_column='ReturnDateTime')),
                ('mileage', models.IntegerField(db_column='Mileage')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('minor_damage', 'Minor Damage'), ('major_damage', 'Major Damage')], db_column='car_condition', max_length=20)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
                ('approved', models.BooleanField(db_column='Approved', default=False)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'car_return',
                'managed': False,
            },
        ),
    ]
