# Generated by Django 5.1 on 2025-12-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationid', models.AutoField(db_column='ReservationID', primary_key=True, serialize=False)),
                ('startdate', models.DateField(db_column='StartDate')),
                ('enddate', models.DateField(db_column='EndDate')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_column='Status', default='pending', max_length=20)),
                ('rejectionreason', models.TextField(blank=True, db_column='RejectionReason', null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Reservation',
                'managed': False,
            },
        ),
    ]
