# Generated by Django 5.1 on 2026-01-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Verify Account'), ('reset', 'Reset Password')], default='verify', max_length=10),
            preserve_default=False,
        ),
    ]
