# Generated by Django 5.2.9 on 2025-12-20 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='document_image',
            field=models.ImageField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
