# Generated by Django 5.1 on 2026-01-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('damageid', models.AutoField(db_column='DamageID', primary_key=True, serialize=False)),
                ('reportdate', models.DateField(db_column='ReportDate')),
                ('description', models.TextField(db_column='Description')),
                ('repaircost', models.DecimalField(blank=True, db_column='RepairCost', decimal_places=2, max_digits=10, null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=255, null=True)),
                ('status', models.CharField(choices=[('reported', 'reported'), ('under_repair', 'under_repair'), ('resolved', 'resolved')], db_column='Status', default='reported', max_length=20)),
                ('handledby', models.BigIntegerField(blank=True, db_column='HandledBy', null=True)),
            ],
            options={
                'db_table': 'damage',
                'managed': False,
            },
        ),
    ]
