# Generated by Django 5.1 on 2025-12-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('reviewdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
    ]
