# Generated by Django 5.2.9 on 2025-12-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carcategory',
            options={'managed': False},
        ),
    ]
