# Generated by Django 5.2.9 on 2025-12-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_alter_carcategory_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
        migrations.AlterModelTable(
            name='carcategory',
            table='carcategory',
        ),
    ]
