# Generated by Django 5.1 on 2026-01-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('system', 'System'), ('notification', 'Notification')], max_length=20)),
                ('value', models.TextField()),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('decimal', 'Decimal'), ('json', 'JSON')], default='string', max_length=10)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_setting',
                'ordering': ['category', 'key_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSettingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_setting_log',
                'ordering': ['-changed_at'],
                'managed': False,
            },
        ),
    ]
