# Generated by Django 5.1 on 2026-01-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.AutoField(db_column='NotificationID', primary_key=True, serialize=False)),
                ('Message', models.TextField(db_column='Message')),
                ('Type', models.CharField(choices=[('reservation', 'reservation'), ('rental', 'rental'), ('payment', 'payment'), ('general', 'general')], db_column='Type', max_length=20)),
                ('SentAt', models.DateTimeField(auto_now_add=True, db_column='SentAt')),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('RecipientID', models.AutoField(db_column='RecipientID', primary_key=True, serialize=False)),
                ('Channel', models.CharField(choices=[('in_app', 'in_app'), ('email', 'email')], db_column='Channel', max_length=10)),
                ('Status', models.CharField(choices=[('unread', 'unread'), ('read', 'read'), ('sent', 'sent'), ('failed', 'failed')], db_column='Status', default='unread', max_length=10)),
                ('SentAt', models.DateTimeField(blank=True, db_column='SentAt', null=True)),
                ('ReadAt', models.DateTimeField(blank=True, db_column='ReadAt', null=True)),
            ],
            options={
                'db_table': 'notification_recipient',
                'managed': False,
            },
        ),
    ]
